stages:
  - build
  - deploy
    #script: ng build && npx scully
#   script: pwd && ls -latr && npm install && /usr/bin/npm run prerender

build_npm:
  stage: build
  script:
    - npm install
    - ng build
    - pwd && ls
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - ./dist
      - ./node_modules

deploy_landing_page:
  stage: deploy
  script:
    - ssh procland@192.168.7.48 'echo "procland" | [ "$( sudo -S /usr/bin/pm2 status main | grep online )" ] && sudo /usr/bin/pm2 stop main || :'
    - ssh procland@192.168.7.48 'echo "procland" | [ -d /var/www/pmi/landing/dist ] && sudo -S rm -rf /var/www/pmi/landing/dist'
    - ssh procland@192.168.7.48 'echo "procland" | [ -d /tmp/dist ] && sudo -S rm -rf /tmp/dist || :'
    - scp -o stricthostkeychecking=no -r ./dist procland@192.168.7.48:/tmp/
    - ssh procland@192.168.7.48 'echo "procland" | [ -d /tmp/dist ] && sudo -S cp -ar /tmp/dist /var/www/pmi/landing/'
    - ssh procland@192.168.7.48 'echo "procland" | sudo -S /usr/bin/pm2 start main'
  environment: 
    name: PROCUREMENT24ORE_LANDINGPAGE
    url: 192.168.7.48:4000
  only:
    - master

after_script:
  - echo "End CI"