#before_script:
#  - export PATH="/opt/jdk11.0.5/bin:$PATH"
    
stages:
  - build
#  - deploy


build:
   stage: build
   script: npm install && /usr/bin/npm run prerender && ls -latr
#   script: pwd && ls -latr && npm install && /usr/bin/npm run prerender
   artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
#    paths:
#      - build/libs/epp.jar

#deploy_albini_dev:
#  stage: deploy
#
#  script:
    #- sshpass -V
    #- export SSHPASS=$USER_ALBINI_DEV_PASS
#    - scp -o stricthostkeychecking=no -r build/libs/epp.jar albinidev@192.168.10.217:/opt/albini-dev
#    - ssh albinidev@192.168.10.217 'echo "albinidev" | sudo -S systemctl restart albini-dev.service'

#  environment:
#    name: ALBINI DEV
#    url: 192.168.10.217
#  when: manual
#  only:
#    - support/EPP-R29-HFIX#1621
#    - feature/EPP-NFET#NIUM-131
#    - hotfix/EPP-R38-HFIX#AS-327


after_script:
  - echo "End CI"


