#before_script:
#  - export PATH="/opt/jdk11.0.5/bin:$PATH"
    
stages:
  - build
  - deploy


build:
   stage: build
   script: npm install && /usr/bin/npm run prerender && ls -latr
#   script: pwd && ls -latr && npm install && /usr/bin/npm run prerender
   artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - ./dist

deploy_procurement24ore-landing-page:
  stage: deploy
 
  script:
    - ssh procland@192.168.7.48 'echo "procland" | [ "$( sudo -S /usr/bin/pm2 status main | grep online )" ] && sudo /usr/bin/pm2 stop main || :'
    - ssh procland@192.168.7.48 'echo "procland" | [ -d /var/www/pmi/landing/dist ] && sudo -S rm -rf /var/www/pmi/landing/dist'
    - ssh procland@192.168.7.48 'echo "procland" | [ -d /tmp/dist ] && sudo -S rm -rf /tmp/dist || :'
    - scp -o stricthostkeychecking=no -r ./dist procland@192.168.7.48:/tmp/
    - ssh procland@192.168.7.48 'echo "procland" | [ -d /tmp/dist ] && sudo -S cp -ar /tmp/dist /var/www/pmi/landing/'
    - ssh procland@192.168.7.48 'echo "procland" | sudo -S /usr/bin/pm2 start main'

  environment:
    name: PROCUREMENT24ORE LANDINGPAGE
    url: 192.168.7.48:4000
#  when: manual
  only:
    - master


after_script:
  - echo "End CI"


