stages:
  - build
  - deploy
    #script: ng build && npx scully
#   script: pwd && ls -latr && npm install && /usr/bin/npm run prerender

build_npm:
  stage: build
  script:
    - ls -l
  srtifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - ./dist

deploy_landing_page:
  stage: deploy
  script:
    - ls -l
  environment: PROCUREMENT24ORE_LANDINGPAGE
  url: 192.168.7.48:4000
  only:
    - master

after_script:
  - echo "End CI"